// parts/WorldScene.js — auto-generated by create_world.
// A working top-down open-world scene: WalkS the player around the world defined
// in G.state.world, follows with the camera, resolves tile collision, and walks
// through portals between areas. Replace _drawPlayer / add logic as you like.
(function (G, GF) {
  'use strict';
  G.scenes.World = class World extends GF.Scene {
    init(engine) {
      this.engine = engine;
      const game = G.game;
      this.game = game;

      // Free 2D top-down movement: disable the flat-floor/wall clamp so the
      // world's collision layer is the only authority.
      const phys = engine.getSystem('PhysicsSystem');
      if (phys) { phys.gravity = 0; phys.floorY = 1e9; phys.leftWall = -1e9; phys.rightWall = 1e9; }

      engine.input
        .bind('up', 'ArrowUp', 'KeyW').bind('down', 'ArrowDown', 'KeyS')
        .bind('left', 'ArrowLeft', 'KeyA').bind('right', 'ArrowRight', 'KeyD');

      this.player = new GF.PhysicsBody({ x: 0, y: 0, width: 20, height: 28,
        gravityScale: 0, maxSpeedX: 400, maxSpeedY: 400, friction: 0.0001, tag: 'player' });
      if (phys) phys.addBody(this.player);

      // World system (added AFTER physics so collision resolves last each frame).
      this.world = new GF.WorldSystem({ viewWidth: engine.config.width, viewHeight: engine.config.height });
      engine.addSystem(this.world);

      // Register any imported spritesheets (import_spritesheet writes these).
      const sheets = (G.state && G.state.sheets) || {};
      Object.keys(sheets).forEach((n) => {
        game.sprites.registerSheet(n, sheets[n].image, sheets[n].atlas);
      });

      // Draw the player with an imported 'hero' sprite if present, else a marker.
      this.facing = 1;
      this.anim = game.sprites.getSprite('hero')
        ? game.sprites.createAnimator('hero', 'idle') : null;
      this.world.setPlayer(this.player, (ctx) => this._drawPlayer(ctx));

      this.world.loadWorld((G.state && G.state.world) || { areas: {} });
    }

    update(dt, engine) {
      const inp = engine.input;
      let vx = 0, vy = 0;
      if (inp.isDown('left'))  { vx -= 1; this.facing = -1; }
      if (inp.isDown('right')) { vx += 1; this.facing = 1; }
      if (inp.isDown('up'))    vy -= 1;
      if (inp.isDown('down'))  vy += 1;
      const speed = 190;
      this.player.vx = vx * speed;
      this.player.vy = vy * speed;
      this.moving = !!(vx || vy);
      if (this.anim) this.anim.play(this.moving && this.anim ? 'walk' : 'idle');
      if (this.anim) this.anim.update(dt);
    }

    render(ctx, engine) {
      this.world.draw(ctx);
      GF.UISystem.drawText(ctx, this.world.areaName || '', 12, 12,
        { font: '16px monospace', color: '#fff' });
      GF.UISystem.drawText(ctx, 'WASD / arrows to explore', 12, 32,
        { font: '12px monospace', color: '#9bd' });
    }

    _drawPlayer(ctx) {
      const b = this.player;
      const x = b.x + b.width / 2, y = b.y + b.height;
      if (this.anim && this.game.sprites.getSprite('hero')) {
        this.anim.flipX = this.facing < 0;
        this.anim.draw(ctx, x, y);
        return;
      }
      ctx.fillStyle = '#ffd24a';
      ctx.fillRect(x - 10, y - 28, 20, 26);
      ctx.fillStyle = '#2e7d32';
      ctx.fillRect(x - 10, y - 12, 20, 12);
      ctx.fillStyle = '#000';
      ctx.fillRect(x + (this.facing < 0 ? -8 : 2), y - 22, 6, 4);
    }
  };
})(window.GAME = window.GAME || { components: {}, scenes: {}, systems: {}, state: {} }, window.GF);
